### ISSUE TITLE
Submitting the form does not work from a frame due to missing `allow-forms` permisison

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-jhub-apps#15]
### Context

Clicking "Next" button in the form does nothing:

![image](https://github.com/user-attachments/assets/e816ebf0-96ba-4a8a-be1b-5f5a7b193128)

Instead error is shown in console

![image](https://github.com/user-attachments/assets/55ad2d54-710a-421e-a60e-474569c8afe3)

### Value and/or benefit

This is critical bug

**Comment by nenb** [comment]
@krassowski Can this be solved by updating the frame sandbox attribute: https://github.com/nebari-dev/jupyterlab-jhub-apps/blob/aa33cc0fe67cb67efefa340ebb912b05e082034f/src/index.ts#L228.

If so, are there any other permissions that you think I should set?

**Comment by krassowski** [comment]
I think so
