### ISSUE TITLE
Clicking on "visit our docs" does nothing when in main area widget

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-jhub-apps#18]
### Context

Clicking the link does not work:

![image](https://github.com/user-attachments/assets/d618c6a9-35f3-4372-9019-b7951db51b34)

This shows an error:

```
Blocked opening 'https://jhub-apps.nebari.dev/docs/category/create-apps' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```

### Value and/or benefit

Let's allow opening popups OR intercept it and open it in new main area widget.

**Comment by nenb** [comment]
@krassowski I think this also relates to my comment on #15. I'll try and address both of these issues in the same PR.
