### ISSUE TITLE
Add "Deploy App" label in toolbar?

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-jhub-apps#2]
### Context

The original mockup included "Deploy App" label in the toolbar:

![image](https://github.com/user-attachments/assets/19c71dc2-0e6f-4db4-9ba9-fe6f1bf226cb)

Let's see if we can add it easily, ideally in a way that does not take up too much space (can we show only "Deploy" if the toolbar is narrow?)

### Value and/or benefit

- (+) Users will have easier time to find the button
- (-) More space taken up in the toolbar

**Comment by nenb** [comment]
**Relevant information**
https://discourse.jupyter.org/t/jl-4-toolbar-button-with-icon-and-text/20519/2
