### ISSUE TITLE
After clicking "Deploy App" in the frame the iframe goes blank

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-jhub-apps#24]
### Context

![refused-to-connect-final-screen](https://github.com/user-attachments/assets/d77ab8b9-0e45-43c2-90c2-a856d259ffff)

```
Refused to frame 'https://nebari/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

### Value and/or benefit

NA

**Comment by krassowski** [comment]
When I use the headless form outside of an iframe it redirects me to a spawn page like `https://nebari/hub/spawn-pending/mike/tes-1771544`

![image](https://github.com/user-attachments/assets/e714af0b-27c2-48d0-9b5c-b7b91d0b6650)

**Comment by krassowski** [comment]
I think we need to either:
- intercept the final redirection and instead show a confirmation that the app was deployed (:tada:) and allow user to click a button to launch it in a new tab (outside of the iframe)
- allow the app to be launched in the iframe by relaxing `frame-ancestors` to `self` (this is easier short-term)

**Comment by nenb** [comment]
>intercept the final redirection and instead show a confirmation that the app was deployed (:tada:) and allow user to click a button to launch it in a new tab (outside of the iframe)

It seems like events like `beforeUnload` etc are only triggered _after_ the CSP violation i.e. the header is checked first before the javascript can be executed. At least, this is my current understanding.

I’m currently unable to think of a way to indirectly intercept/prevent the navigate [request](https://github.com/nebari-dev/jhub-apps/blob/1961353994f9406ac8a445fe42d0351b82f5b800/ui/src/components/app-form/app-form.tsx#L274).

I guess an alternative is for me to open another PR in jhub-apps (unless you can think of another workaround)? e.g. if we are in headless mode (see [this](https://github.com/nebari-dev/jhub-apps/blob/1961353994f9406ac8a445fe42d0351b82f5b800/ui/src/components/app-form/app-form.tsx#L65) variable) then we have no navigation. What do you think?

**Comment by krassowski** [comment]
> I’m currently unable to think of a way to indirectly intercept/prevent the navigate [request](https://github.com/nebari-dev/jhub-apps/blob/1961353994f9406ac8a445fe42d0351b82f5b800/ui/src/components/app-form/app-form.tsx#L274).

As per https://developer.mozilla.org/en-US/docs/Web/API/Location/assign#exceptions the assign should throw [`SecurityError`](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign#securityerror) exception so maybe it should be fixed on jhub-apps by catching this exception and in that case showing a confirmation screen and a button allowing to open that URL in a new browser tab?

**Comment by krassowski** [comment]
> if we are in headless mode (see [this](https://github.com/nebari-dev/jhub-apps/blob/1961353994f9406ac8a445fe42d0351b82f5b800/ui/src/components/app-form/app-form.tsx#L65) variable) then we have no navigation.

That would work too. Still, need to show a confirmation and have a way to open it in new window.

**Comment by nenb** [comment]
@krassowski If you are agreed that this issue is probably best resolved in `jhub-apps` (perhaps with some downstream tweaks afterwards here if required), then I will open an issue in `jhub-apps` now.

**Comment by krassowski** [comment]
Yes, let's do that!

**Comment by nenb** [comment]
I believe that this has now been closed by https://github.com/nebari-dev/jhub-apps/pull/509.
