### ISSUE TITLE
Add button to the File Editor toolbar

### ISSUE THREAD

**Issue by krassowski** [nebari-dev/jupyterlab-jhub-apps#3]
### Context

In addition to the button on the Notebook toolbar, the mockups asked for a button in the file editor:

![image](https://github.com/user-attachments/assets/92656fdf-00c7-4805-aed9-b9e60f1bc41f)

### Value and/or benefit

- (+) Users will be able to deploy current file with one-click
- (-) The toolbar in file browser will show up if no other extension already added buttons; in nebari/jhub-apps context there would already be a button added by Panel (Panel preview) so this is not a big downside

**Comment by nenb** [comment]
Closing after merging #9
